type Chat = Awaited<
  ReturnType<typeof import("@/lib/data/chat/chat.service").getChatsForUser>
>;

export const userId1 = "user123";
export const userId2 = "user456";
export const userId3 = "user789";
export const userId4 = "user101112";

// Helper to generate random messages
function generateMessages(chatId: string, count: number) {
  return Array.from({ length: count }).map((_, idx) => ({
    id: `${chatId}-msg${idx + 1}`,
    chatId,
    userId: `member${chatId.replace("chat", "")}`,
    text: `Random message ${idx + 1} in ${chatId}`,
    createdAt: new Date(Date.now() - Math.floor(Math.random() * 10000000)),
  }));
}

export const mockChats: Chat = [
  {
    id: "chat1",
    createdAt: new Date(Date.now()),
    members: [
      {
        createdAt: new Date(Date.now()),
        id: "member1",
        chatId: "chat1",
        userId: userId1,
        user: {
          clerkUserId: userId1,
          createdAt: new Date(Date.now()),
          updatedAt: new Date(Date.now()),
          lastActive: new Date(Date.now()),
          online: true,
          Profile: {
            name: "Alice",
            height: 170,
            weight: 60,
            bio: "Hello, I am Alice.",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
            id: "",
            userId: "",
            sexRole: null,
            date_of_birth: new Date("2000-01-01"),
            avatar: null,
          },
        },
      },
      {
        createdAt: new Date(Date.now()),
        id: "member1b",
        chatId: "chat1",
        userId: userId3,
        user: {
          clerkUserId: userId3,
          createdAt: new Date(Date.now()),
          updatedAt: new Date(Date.now()),
          lastActive: new Date(Date.now()),
          online: false,
          Profile: {
            name: "User3",
            height: 165,
            weight: 65,
            bio: "User3's bio.",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
            id: "",
            userId: "",
            sexRole: null,
            date_of_birth: new Date("1993-03-03"),
            avatar: null,
          },
        },
      },
    ],
    messages: generateMessages("chat1", 3),
    _count: {
      messages: 3,
    },
  },
  {
    id: "chat2",
    createdAt: new Date(Date.now()),
    members: [
      {
        createdAt: new Date(Date.now()),
        id: "member2",
        chatId: "chat2",
        userId: userId1,
        user: {
          clerkUserId: userId1,
          createdAt: new Date(Date.now()),
          updatedAt: new Date(Date.now()),
          lastActive: new Date(Date.now()),
          online: true,
          Profile: {
            name: "Bob",
            height: 180,
            weight: 75,
            bio: "Hey, I'm Bob.",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
            id: "",
            userId: "",
            sexRole: null,
            date_of_birth: new Date("1995-05-15"),
            avatar: null,
          },
        },
      },
      {
        createdAt: new Date(Date.now()),
        id: "member2b",
        chatId: "chat2",
        userId: userId2,
        user: {
          clerkUserId: userId2,
          createdAt: new Date(Date.now()),
          updatedAt: new Date(Date.now()),
          lastActive: new Date(Date.now()),
          online: false,
          Profile: {
            name: "User2",
            height: 175,
            weight: 70,
            bio: "User2's bio.",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
            id: "",
            userId: "",
            sexRole: null,
            date_of_birth: new Date("1992-02-02"),
            avatar: null,
          },
        },
      },
    ],
    messages: generateMessages("chat2", 2),
    _count: {
      messages: 2,
    },
  },
  {
    id: "chat3",
    createdAt: new Date(Date.now()),
    members: [
      {
        createdAt: new Date(Date.now()),
        id: "member3",
        chatId: "chat3",
        userId: userId1,
        user: {
          clerkUserId: userId1,
          createdAt: new Date(Date.now()),
          updatedAt: new Date(Date.now()),
          lastActive: new Date(Date.now()),
          online: false,
          Profile: {
            name: "Charlie",
            height: 165,
            weight: 68,
            bio: "Charlie here.",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
            id: "",
            userId: "",
            sexRole: null,
            date_of_birth: new Date("1992-03-10"),
            avatar: null,
          },
        },
      },
    ],
    messages: generateMessages("chat3", 4),
    _count: {
      messages: 4,
    },
  },
  {
    id: "chat4",
    createdAt: new Date(Date.now()),
    members: [
      {
        createdAt: new Date(Date.now()),
        id: "member4",
        chatId: "chat4",
        userId: userId1,
        user: {
          clerkUserId: userId1,
          createdAt: new Date(Date.now()),
          updatedAt: new Date(Date.now()),
          lastActive: new Date(Date.now()),
          online: true,
          Profile: {
            name: "Diana",
            height: 160,
            weight: 55,
            bio: "Diana's bio.",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
            id: "",
            userId: "",
            sexRole: null,
            date_of_birth: new Date("1998-07-22"),
            avatar: null,
          },
        },
      },
    ],
    messages: generateMessages("chat4", 1),
    _count: {
      messages: 1,
    },
  },
  {
    id: "chat5",
    createdAt: new Date(Date.now()),
    members: [
      {
        createdAt: new Date(Date.now()),
        id: "member5",
        chatId: "chat5",
        userId: userId1,
        user: {
          clerkUserId: userId1,
          createdAt: new Date(Date.now()),
          updatedAt: new Date(Date.now()),
          lastActive: new Date(Date.now()),
          online: false,
          Profile: {
            name: "Eve",
            height: 175,
            weight: 65,
            bio: "Eve here.",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
            id: "",
            userId: "",
            sexRole: null,
            date_of_birth: new Date("1990-12-05"),
            avatar: null,
          },
        },
      },
    ],
    messages: generateMessages("chat5", 0),
    _count: {
      messages: 0,
    },
  },
  {
    id: "chat6",
    createdAt: new Date(Date.now()),
    members: [
      {
        createdAt: new Date(Date.now()),
        id: "member6",
        chatId: "chat6",
        userId: userId1,
        user: {
          clerkUserId: userId1,
          createdAt: new Date(Date.now()),
          updatedAt: new Date(Date.now()),
          lastActive: new Date(Date.now()),
          online: true,
          Profile: {
            name: "Frank",
            height: 185,
            weight: 80,
            bio: "Frank's profile.",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
            id: "",
            userId: "",
            sexRole: null,
            date_of_birth: new Date("1988-09-30"),
            avatar: null,
          },
        },
      },
      {
        createdAt: new Date(Date.now()),
        id: "member6b",
        chatId: "chat6",
        userId: userId4,
        user: {
          clerkUserId: userId4,
          createdAt: new Date(Date.now()),
          updatedAt: new Date(Date.now()),
          lastActive: new Date(Date.now()),
          online: false,
          Profile: {
            name: "User4",
            height: 170,
            weight: 75,
            bio: "User4's bio.",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
            id: "",
            userId: "",
            sexRole: null,
            date_of_birth: new Date("1994-04-04"),
            avatar: null,
          },
        },
      },
    ],
    messages: generateMessages("chat6", 5),
    _count: {
      messages: 5,
    },
  },
  // New users start here
  {
    id: "chat7",
    createdAt: new Date(Date.now()),
    members: [
      {
        createdAt: new Date(Date.now()),
        id: "member7",
        chatId: "chat7",
        userId: userId1,
        user: {
          clerkUserId: userId1,
          createdAt: new Date(Date.now()),
          updatedAt: new Date(Date.now()),
          lastActive: new Date(Date.now()),
          online: false,
          Profile: {
            name: "Grace",
            height: 168,
            weight: 58,
            bio: "Grace's intro.",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
            id: "",
            userId: "",
            sexRole: null,
            date_of_birth: new Date("1993-11-11"),
            avatar: null,
          },
        },
      },
    ],
    messages: generateMessages("chat7", 2),
    _count: {
      messages: 2,
    },
  },
  {
    id: "chat8",
    createdAt: new Date(Date.now()),
    members: [
      {
        createdAt: new Date(Date.now()),
        id: "member8",
        chatId: "chat8",
        userId: userId1,
        user: {
          clerkUserId: userId1,
          createdAt: new Date(Date.now()),
          updatedAt: new Date(Date.now()),
          lastActive: new Date(Date.now()),
          online: true,
          Profile: {
            name: "Henry",
            height: 172,
            weight: 70,
            bio: "Henry's bio.",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
            id: "",
            userId: "",
            sexRole: null,
            date_of_birth: new Date("1997-04-18"),
            avatar: null,
          },
        },
      },
    ],
    messages: generateMessages("chat8", 3),
    _count: {
      messages: 3,
    },
  },
  {
    id: "chat9",
    createdAt: new Date(Date.now()),
    members: [
      {
        createdAt: new Date(Date.now()),
        id: "member9",
        chatId: "chat9",
        userId: userId1,
        user: {
          clerkUserId: userId1,
          createdAt: new Date(Date.now()),
          updatedAt: new Date(Date.now()),
          lastActive: new Date(Date.now()),
          online: false,
          Profile: {
            name: "Ivy",
            height: 162,
            weight: 54,
            bio: "Ivy's profile.",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
            id: "",
            userId: "",
            sexRole: null,
            date_of_birth: new Date("1999-08-25"),
            avatar: null,
          },
        },
      },
    ],
    messages: generateMessages("chat9", 1),
    _count: {
      messages: 1,
    },
  },
  {
    id: "chat10",
    createdAt: new Date(Date.now()),
    members: [
      {
        createdAt: new Date(Date.now()),
        id: "member10",
        chatId: "chat10",
        userId: userId1,
        user: {
          clerkUserId: userId1,
          createdAt: new Date(Date.now()),
          updatedAt: new Date(Date.now()),
          lastActive: new Date(Date.now()),
          online: true,
          Profile: {
            name: "Jack",
            height: 178,
            weight: 77,
            bio: "Jack's story.",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
            id: "",
            userId: "",
            sexRole: null,
            date_of_birth: new Date("1991-02-14"),
            avatar: null,
          },
        },
      },
    ],
    messages: generateMessages("chat10", 4),
    _count: {
      messages: 4,
    },
  },
];
